version: "3.5"

services:
  sonarqube:
    image: sonarqube
    container_name: sonarqube
    ports:
      - "9000:9000"
    networks:
      - db-poc-sonar-network
    environment:
      - SONARQUBE_JDBC_URL=jdbc:postgresql://db-poc:5432/sonar
    volumes:
      - db-poc-sonarqube_conf:/opt/sonarqube/conf
      - db-poc-sonarqube_data:/opt/sonarqube/data
      - db-poc-sonarqube_extensions:/opt/sonarqube/extensions
      - db-poc-sonarqube_bundled-plugins:/opt/sonarqube/lib/bundled-plugins
  jenkins:
    image: 'bitnami/jenkins:2'
    environment: 
      - JENKINS_USERNAME=admin
      - JENKINS_PASSWORD=admin
    ports:
      - 8080:8080
      - 443:8443
      - 50000:50000
    volumes:
      - 'jenkins_data:/bitnami'

  db-poc:
    image: postgres
    container_name: db-poc-sonarqube-db
    networks:
      - db-poc-sonar-network
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - db-poc-sonarqube_psql:/var/lib/postgresql
      - db-poc-sonarqube_psql_data:/var/lib/postgresql/data

      
networks: 
  db-poc-sonar-network:
    name: db-poc-sonar-network
    driver: bridge

volumes:
  db-poc-sonarqube_conf:
  db-poc-sonarqube_data:
  db-poc-sonarqube_extensions:
  db-poc-sonarqube_bundled-plugins:
  db-poc-sonarqube_psql:
  db-poc-sonarqube_psql_data:
  jenkins_data:
    driver: local
